### ISSUE TITLE
JVM access to processId has become a fatal error in Java 17.

### ISSUE THREAD

**Issue by jmacauley** [BandwidthOnDemand/nsi-dds#18]
In Java 17 the following JVM access has become a fatal error:
```
  private static int getProcessId(RuntimeMXBean mxBean) throws NoSuchFieldException, IllegalArgumentException,
          IllegalAccessException, NoSuchMethodException, InvocationTargetException {
    java.lang.reflect.Field jvm = mxBean.getClass().getDeclaredField("jvm");
    jvm.setAccessible(true);
    Object mgmt = jvm.get(mxBean);
    java.lang.reflect.Method pid_method = mgmt.getClass().getDeclaredMethod("getProcessId");
    pid_method.setAccessible(true);
    return (int) pid_method.invoke(mgmt);
  }
```
The following error is being generated:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final sun.management.VMManagement sun.management.RuntimeImpl.jvm accessible: module java.management does not "opens sun.management" to unnamed module @3b81a1bc
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at net.es.nsi.dds.server.Main.getProcessId(Main.java:291)
	at net.es.nsi.dds.server.Main.getPid(Main.java:269)
	at net.es.nsi.dds.server.Main.processPidFile(Main.java:240)
	at net.es.nsi.dds.server.Main.processOptions(Main.java:118)
	at net.es.nsi.dds.server.Main.main(Main.java:54)
	... 6 more
```

**Comment by jmacauley** [comment]
Fixed with update https://github.com/BandwidthOnDemand/nsi-dds/pull/19/commits/9b406f2420e1a53fe1512b2679f9dd9c98798854.
